DB: Implemented schema for database
amitsaini4556/FacultyRecruitment pull request #10
Opened 2021-05-16 12:51 UTC by MuskanPaliwal

Have not tested the schema yet as I wanted to be sure with the fields we are adding in the tables. Please let me know if there is some fields left out in the tables.

2021-05-16 13:45 UTC, amitsaini4556 requested changes

2021-05-16 13:45 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    jobId = models.CharField(primary_key=True, max_length=10)
I think jobId is an integer type, not a character? 
or replace Chatfield with AutoField and remove max_length constraint.

2021-05-16 13:45 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +
ImageField missing for the image.

2021-05-16 13:45 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    email= models.CharField(max_length=40)
use EmailField for the email field

2021-05-16 13:45 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    phoneNumber = models.CharField(max_length=12)
use PhoneField

2021-05-16 14:09 UTC, hemabhagnani requested changes

2021-05-16 14:09 UTC, hemabhagnani commented on facultyRecruitment/jobs/models.py
> +    collegeName = models.CharField(max_length=50)
As we have limited values shouldn't we use choices in `collegeName` ?

2021-05-16 14:17 UTC, MuskanPaliwal commented on facultyRecruitment/jobs/models.py
> +    jobId = models.CharField(primary_key=True, max_length=10)
Alright.

2021-05-16 14:21 UTC, hemabhagnani commented on facultyRecruitment/jobs/models.py
> +    jobId = models.ForeignKey(Jobs, on_delete=models.CASCADE, unique=True)
`userId` and `jobId` must be used as a composite primary key

2021-05-16 15:33 UTC, MuskanPaliwal commented on facultyRecruitment/jobs/models.py
> +    email= models.CharField(max_length=40)
applied the changes.

2021-05-16 15:43 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
Applicants fill resume or cv as a link(drive link) or file(Pdf)?

2021-05-16 16:12 UTC, hemabhagnani approved these changes

2021-05-16 16:13 UTC, hemabhagnani commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
Yes, it will be drive links for now, later will work on incorporating pdfs as well.

2021-05-16 16:25 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
yet not ? I think choose a file is easy rather than copy or paste the link of drive.

2021-05-16 19:13 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
Replace `urlField` by `FileField` for both resume or cv.

2021-05-17 04:28 UTC, MuskanPaliwal commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
[saving-files-in-database](https://stackoverflow.com/questions/38628770/how-to-save-files-to-database-in-django), the answer to the question clearly suggests that it is a bad idea to store files in the DB instead we could use external storage for storing files. Here are a bunch of nice options to go for [Django-Storage-Options](https://django-storages.readthedocs.io/en/latest/).

2021-05-18 11:44 UTC, amitsaini4556 commented on facultyRecruitment/jobs/models.py
> +    cv = models.URLField(max_length=200)
ok, go for it.

2021-05-19 13:51 UTC, amitsaini4556 approved these changes

2021-05-19 13:51 UTC, merged