Level-wise view added for Admin or Applicants
amitsaini4556/FacultyRecruitment pull request #15
Opened 2021-05-19 07:23 UTC by amitsaini4556

### View For Admin
![Screenshot (15)](https://user-images.githubusercontent.com/54165387/118771739-845e9000-b8a0-11eb-953f-1e81c139ca0c.png)

### View For Applicants
![Screenshot (16)](https://user-images.githubusercontent.com/54165387/118771733-8294cc80-b8a0-11eb-886f-3fbf9f2c5c1d.png)

fixes issue #14

2021-05-20 13:29 UTC, MuskanPaliwal commented on facultyRecruitment/userAccounts/views.py
> +			user.groups.add(group)
would like to know that why have we created a group of users? We only have two types of user role in the application. How using groups here is a better idea here?

2021-05-20 14:36 UTC, amitsaini4556 commented on facultyRecruitment/userAccounts/views.py
> +			user.groups.add(group)
There are two groups one is`admin` and another `candidates` already created by django backend admin's site.
All users added in `admin` behave like a staff and on the other hand `candidates` group as a active user only.

2021-05-20 14:44 UTC, hemabhagnani approved these changes

2021-05-21 04:54 UTC, MuskanPaliwal commented on facultyRecruitment/userAccounts/views.py
> +			user.groups.add(group)
Okay. Get it.

2021-05-21 05:03 UTC, MuskanPaliwal requested changes
Please check the indentation once.

2021-05-21 05:03 UTC, MuskanPaliwal commented on facultyRecruitment/templates/jobs/addJobForm.html
> +
Unwanted blank line. Please remove it

2021-05-21 05:03 UTC, MuskanPaliwal commented on facultyRecruitment/templates/jobs/addJobForm.html
> +
please remove the blank line.

2021-05-21 05:03 UTC, MuskanPaliwal commented on facultyRecruitment/templates/jobs/addJobForm.html
> +</script>
please indent it properly.

2021-05-21 05:03 UTC, MuskanPaliwal commented on facultyRecruitment/templates/jobs/addJobForm.html
>  						</div>
only one Tab is required for `Reset` word.

2021-05-21 09:34 UTC, amitsaini4556 commented on facultyRecruitment/templates/jobs/addJobForm.html
> +
the blank line used for clear understanding.

2021-05-21 09:43 UTC, amitsaini4556 commented on facultyRecruitment/templates/jobs/addJobForm.html
>  						</div>
### It's looking good in my ide.
![image](https://user-images.githubusercontent.com/54165387/119117549-f670d980-ba46-11eb-93f1-2078db6342dc.png)

2021-05-21 09:49 UTC, amitsaini4556 commented on facultyRecruitment/templates/jobs/addJobForm.html
> +</script>
It will be done in nxt PR.

2021-05-21 10:01 UTC, MuskanPaliwal approved these changes

2021-05-21 10:03 UTC, merged