SugnUP UI added with functionality
amitsaini4556/FacultyRecruitment pull request #7
Opened 2021-05-05 11:09 UTC by amitsaini4556

2021-05-05 11:23 UTC, MuskanPaliwal requested changes

2021-05-05 11:23 UTC, MuskanPaliwal commented on facultyRecruitment/userAccounts/forms.py
> +	def clean_email(self):
Just wondering, why is this named `clean_email`?

2021-05-05 11:23 UTC, MuskanPaliwal commented on facultyRecruitment/userAccounts/forms.py
> +		if validate_email(email,verify=True) == True:
the `validate_email` is a function, right? and it returns a boolean value. I would like to suggest that the function should completely validate the email and return the error(`ValidationError`) or a response.

2021-05-05 11:30 UTC, MuskanPaliwal commented on facultyRecruitment/userAccounts/forms.py
> +		if validate_email(email,verify=True) == True:
oh, it is an external library function.

2021-05-05 11:41 UTC, MuskanPaliwal approved these changes

2021-05-05 11:44 UTC, merged

2021-05-11 12:30 UTC, amitsaini4556 commented on facultyRecruitment/userAccounts/forms.py
> +	def clean_email(self):
we can't change the method prefix 'clean'. 
In Django, It's the predefined syntax for validating parameters so we can't override.